name = "youtube-seo-booster-v21"
main = "worker.js"
compatibility_date = "2026-08-07"

[assets]
directory = "./"
binding = "ASSETS"

[[kv_namespaces]]
binding = "CACHE"
id = "379f571e20114ccb87d459ebe1ea47dd"
